<?php

/**
 * @file
 * Contains journal_types.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\journal_types\CitationTools;
use Drupal\pathauto\Entity\PathautoPattern;
/**
 * Implements hook_help().
 */
function journal_types_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the journal_types module.
    case 'help.page.journal_types':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Content types for scholarly content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function journal_types_theme() {
  return [
    'journal_types' => [
      'render element' => 'children',
    ],
  ];
}

function journal_types_pathauto_pattern_alter(PathautoPattern &$pattern, array $context) {
  if ($context['module'] == 'node' && ($context['op'] == 'insert' || $context['op'] == 'update')) {

    /** @var \Drupal\node\Entity\Node $node */
    $node = $context['data']['node'];
    switch ($node->getType()) {
      case 'journal_article':
        $citationTools = new CitationTools();
        $citation_metadata = $citationTools->getCitationMetadataForArticle($node);
        $year = $citation_metadata['bibcite_year'][0]['value'];
        $volume = $citation_metadata['bibcite_volume'][0]['value'];
        $number = $citation_metadata['bibcite_number'][0]['value'];
        $cleaner = \Drupal::service('pathauto.alias_cleaner');
        $slug = 'article/' . (!empty($year) ? $cleaner->cleanString($year) . '/' : '' )
          . (!empty($volume) ? $cleaner->cleanString($volume) . '/' : '')
          . (!empty($number) ? $cleaner->cleanString($number) . '/' : '')
          . '[node:title]';

        // Replace default [node:title] with logic-derived tokens.
        $pattern->setPattern(preg_replace('/\[node:title(\:[^]]*)?\]/', $slug . '$1', $pattern->getPattern()));
        break;
    }

  }
}

