<?php

/**
 * Workaround because custom field permissions are not exporting properly.
 * Limit who can view the 'assigned reviewer' field to only Journal and Issue reviewwers.
 *
 * @param array $modules
 */
function journal_peer_review_modules_installed(array $modules) {
  $role_storage = \Drupal::service('entity_type.manager')->getStorage('user_role');
  $perms = [
    'create field_peer_reviewer' => [
      'journal_reviewer',
      'issue_reviewer',
    ],
    'edit field_peer_reviewer' => [
      'journal_reviewer',
      'issue_reviewer',
    ],
    'view field_peer_reviewer' => [
      'journal_reviewer',
      'issue_reviewer',
    ],
  ];
  $roles = [];
  foreach ($perms as $permission_name => $role_names) {
    foreach ($role_names as $role_name) {
      $roles[$role_name] = $role_storage->load($role_name);
      $roles[$role_name]->grantPermission($permission_name);
    }
  }

  // Save all roles.
  foreach ($roles as $role) {
    $role->trustData()->save();
  }
}
